apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: parser
  labels:
    app: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      name: parser
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: dealfa/video-shoper-parser:v1.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
          envFrom:
            - secretRef:
                name: tg-bot-secret
          ports:
            - containerPort: 80
              protocol: TCP
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      restartPolicy: Always
