apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
helmCharts:
- name: traefik
  repo: https://traefik.github.io/charts
  releaseName: traefik
  namespace: traefik
  version: 37.4.0
  valuesFile: ./traefik.values.yml
  valuesMerge: merge
  includeCRDs: true