apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nodeexporter
helmCharts:
- name: prometheus-node-exporter
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: node-exporter
  namespace: monitoring
  version: 4.49.2
  valuesFile: values.yaml
  valuesMerge: merge
  includeCRDs: true