apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
helmCharts:
- name: grafana
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  namespace: monitoring
  version: 10.3.1
  valuesFile: values.yaml
  valuesMerge: merge
  includeCRDs: true