- name: upgrade packages
  apt:
    update_cache: true
  ignore_errors: true
- name: install {{ apt_python_packages }} with apt
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_python_packages }}"
- name: install required pip packages {{ pip_packages }}
  pip:
    name: "{{ item.name }}=={{ item.version }}"
  loop: "{{ pip_packages }}"